image: golang:1.11

stages:
  - build

build-win64-executable:
  stage: build
#  only:
#    - stable
  script:
    - mkdir binaries
    - GOOS=windows GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH.exe VlanLister.go

build-linux64-executable:
  stage: build
#  only:
#    - stable
  script:
    - mkdir binaries
    - GOOS=linux GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH VlanLister.go

build-darwin64-executable:
  stage: build
#  only:
#    - stable
  script:
    - mkdir binaries
    - GOOS=darwin GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH VlanLister.go

