image: golang:1.13

stages:
  - build

before_script:
  - mkdir -p binaries
  - go get gitlab.com/rbrt-weiler/go-module-xmcnbiclient

build-win64-executable:
  stage: build
  only:
    - stable
  script:
    - GOOS=windows GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH.exe VlanLister.go

build-linux64-executable:
  stage: build
  only:
    - stable
  script:
    - GOOS=linux GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH VlanLister.go

build-darwin64-executable:
  stage: build
  only:
    - stable
  script:
    - GOOS=darwin GOARCH=amd64 go build -o binaries/VlanLister_$GOOS_$GOARCH VlanLister.go
